const LIBRARY = {
  budget: { cn: "预算" },
  reference: { cn: "参照" },
  "daily budget": { cn: "日预算" },
  cancel: { cn: "取消" },
  save: { cn: "保存" },
  clear: { cn: "清空" },
  "create currency": { cn: "创建货币" },
  add: { cn: "添加" },
  currency: { cn: "货币" },
  savings: { cn: "积蓄" },
  "please enter your daily budget. ": { cn: "请输入你的日预算。" },
  "daily budget cannot be negative. ": { cn: "日预算不可以是负的。" },
  "new budget will start tomorrow.": { cn: "明天将使用新的预算。" },
  "set your daily budget.": { cn: "输入您的预算。" },
  "what is the new currency? ": { cn: "新货币是什么？" },
  "currency with 3 letters only. ": { cn: "货币只能由三个字母组成。" },
  "you already have this currecny. ": { cn: "您已经有这个货币了。" },
  "please add your savings. ": { cn: "请输入您的积蓄。" },
  "new currency added.": { cn: "新的货币已添加。" },
  "savings to start": { cn: "初始积蓄" },
  "how much did you spend? ": { cn: "数额是多少？" },
  "positive amount only please. ": { cn: "请输入正数。" },
  "what did you use this for? ": { cn: "什么分类？" },
  "entry added.": { cn: "条目已添加。" },
  spending: { cn: "消费" },
  earning: { cn: "收入" },
  amount: { cn: "数额" },
  description: { cn: "分类" },
  "how much": { cn: "多少" },
  "for what": { cn: "什么分类" },
  "log entry": { cn: "记录条目" },
  currencies: { cn: "货币" },
  journal: { cn: "账本" },
  schedules: { cn: "定期项" },
  income: { cn: "收入" },
  help: { cn: "帮助" },
  "what's the amount? ": { cn: "数额是多少？" },
  "please select a type. ": { cn: "请选择间隔。" },
  "please select a day. ": { cn: "请选择日或日期。" },
  "schedule added.": { cn: "定期项已添加。" },
  "create schedule": { cn: "创建定期项" },
  "payment": { cn: "支出" },
  "select monthly or weekly": { cn: "选择间隔" },
  "monthly or weekly": { cn: "每月或每星期" },
  "select the day/date": { cn: "选择日或日期" },
  when: { cn: "哪一天" },
  "day/date": { cn: "日/日期" },
  monthly: { cn: "每月" },
  weekly: { cn: "每星期" },
  monday: { cn: "星期一" },
  tuesday: { cn: "星期二" },
  wednesday: { cn: "星期三" },
  thursday: { cn: "星期四" },
  friday: { cn: "星期五" },
  saturday: { cn: "星期六" },
  sunday: { cn: "星期天" },
  type: { cn: "间隔" },
  "you cannot delete the last currency you have.": { cn: "无法删除唯一的货币。" },
  "you cannot delete the currency you are using.": { cn: "无法删除正在使用的货币。" },
  "currency deleted.": { cn: "货币已删除。" },
  "are you sure you want to delete ": { cn: "确定删除" },
  "this action is not reversible.": { cn: "这一操作无法撤销。" },
  yes: { cn: "是" },
  no: { cn: "否" },
  "welcome to dba!": { cn: "欢迎使用DBA！" },
  "start dba": { cn: "开始DBA" },
  "i'm earning": { cn: "我有收入" },
  "total income": { cn: "总收入" },
  "remaining income": { cn: "剩余收入" },
  "days covered": { cn: "剩余天数" },
  "log income": { cn: "记录收入" },
  "income added.": { cn: "收入已添加。" },
  "date": { cn: "日期" },
  "no schedules.": { cn: "空" },
  day: { cn: "日" },
  on: { cn: "" },
  "schedule deleted": { cn: "定期项已删除。" },
  "use this currency": { cn: "使用此货币" },
  "using this currency": { cn: "正在使用此货币" },
  "will use this currency": { cn: "将会使用此货币" },
  "you will be using this currency tomorrow.": { cn: "明日将会使用此货币。" },
  "go and earn some money. this page is useless now.": { cn: "去赚点钱吧。这一页面没什么用了。" },
  "you are spending way ahead of budget. please control your spending.": { cn: "您的消费已经超出您的预算。请控制您的消费。" },
  "you are running out of budget.": { cn: "您的预算即将用完。" },
  warning: { cn: "警告" },
  today: { cn: "今天" },
  "this month": { cn: "本月" },
  overall: { cn: "总结" },
  allowance: { cn: "放心消费额" }
}
export const L = (word, language) => {
  if (language === "en") {
    return word
  } else {
    try {
      return LIBRARY[word.toLowerCase()][language]
    } catch{ return word }
  }
}
